title: Soodoleye
author: Soojin Park
email: rmdwjdtnwls@naver.com
description: # this means to ignore newlines until "baseurl:"
  To be ITdesigner who can give people comfort and joy 
  
# social links
github_username:  pkcpsjwith 

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
